### ISSUE TITLE
DOB to be French formated in UIN card

### ISSUE THREAD

**Issue by wuritechteam** [WuriGuinea/mosip-guinea-ref-impl#234]
Please fixe it to match the DD/MM/YYYY format.

![image](https://user-images.githubusercontent.com/64075677/93763778-8d0fa100-fc01-11ea-82d9-07baa2f753e8.png)

**Comment by hosurkrishnan** [comment]
Fixed in two places, the following re the pull-requests waiting to be merged.

https://github.com/WuriGuinea/mosip-guinea-ref-impl/pull/237/commits/5acd9310d9c4b211f9c869d4a5d4480d5756b37e

https://github.com/WuriGuinea/wuriguinea-mosip-infra/pull/1/commits/eaf13858b628137505061e4215c99f0efc7eb44f

After it is merged, it is required to restarted reg proc and verified.

**Comment by wuritechteam** [comment]
@ankitvaishnav to deploy packetGenerator module and test .
ETA = Oct 06

**Comment by ankitvaishnav** [comment]
PR added

**Comment by wuritechteam** [comment]
@ankitvaishnav to raise PR today targeting **DEV**

**Comment by tisshadjac** [comment]
pending verification

**Comment by wuritechteam** [comment]
@ankitvaishnav to debug today

**Comment by ankitvaishnav** [comment]
Current status: debugging

**Comment by wuritechteam** [comment]
Pending TEST. 
@Goumou7 to test and close

**Comment by wuritechteam** [comment]
Pending TEST.
@Goumou7 to test and close on Monday Oct 19

**Comment by tisshadjac** [comment]
pending test @Goumou7

**Comment by wuritechteam** [comment]
[1 (1).pdf](https://github.com/WuriGuinea/mosip-guinea-ref-impl/files/5415142/1.1.pdf)
Solved and tested.
